### ISSUE TITLE
Strict Notice: Dotdigitalgroup_Email_Model_Customer not compatible with Mage_Customer_Model_Customer

### ISSUE THREAD

**Issue by steverobbins** [dotmailer/dotmailer-magento-extension#179]
Magento CE 1.9.3.0

Trace:

```
Strict Notice: Declaration of Dotdigitalgroup_Email_Model_Customer::sendNewAccountEmail() should be compatible with Mage_Customer_Model_Customer::sendNewAccountEmail($type = 'registered', $backUrl = '', $storeId = '0', $password = '')  in /var/www/html/app/code/community/Dotdigitalgroup/Email/Model/Customer.php on line 4

#0 /var/www/html/app/code/community/Dotdigitalgroup/Email/Model/Customer.php(4): mageCoreErrorHandler(2048, 'Declaration of ...', '/var/ww...', 4, Array)
#1 /var/www/html/lib/Varien/Autoload.php(94): include('/var/ww...')
#2 [internal function]: Varien_Autoload->autoload('Dotdigitalgroup...')
#3 [internal function]: spl_autoload_call('Dotdigitalgroup...')
#4 /var/www/html/app/code/core/Mage/Core/Model/Config.php(1355): class_exists('Dotdigitalgroup...')
#5 /var/www/html/app/Mage.php(463): Mage_Core_Model_Config->getModelInstance('customer/custom...', Array)
#6 /var/www/html/app/code/community/Dotdigitalgroup/Email/Model/Adminhtml/Source/Customer/Attributes/Select.php(22): Mage::getModel('customer/custom...')
#7 /var/www/html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(463): Dotdigitalgroup_Email_Model_Adminhtml_Source_Customer_Attributes_Select->toOptionArray(false)
#8 /var/www/html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(229): Mage_Adminhtml_Block_System_Config_Form->initFields(Object(Varien_Data_Form_Element_Fieldset), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#9 /var/www/html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(164): Mage_Adminhtml_Block_System_Config_Form->_initGroup(Object(Varien_Data_Form), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#10 /var/www/html/app/code/core/Mage/Adminhtml/Block/System/Config/Edit.php(92): Mage_Adminhtml_Block_System_Config_Form->initForm()
#11 /var/www/html/app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(107): Mage_Adminhtml_Block_System_Config_Edit->initForm()
#12 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_System_ConfigController->editAction()
#13 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('edit')
#14 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#15 /var/www/html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#16 /var/www/html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#17 /var/www/html/index.php(83): Mage::run('wholesale', 'store')
#18 {main}
```

**Comment by cdiacon** [comment]
Hey @steverobbins what is the connector version you are using ?

**Comment by steverobbins** [comment]
@cdiacon The latest, v6.2.4.

```
$ grep version app/code/community/Dotdigitalgroup/Email/etc/config.xml
<?xml version="1.0"?>
            <version>6.2.4</version>
```

**Comment by cdiacon** [comment]
This should fix the issue https://github.com/cdiacon/dotmailer-magento-extension/commit/c0ad71e621ba27561c329819f5a982e4a4ec0a64?diff=split

**Comment by steverobbins** [comment]
Will you be merging #164 into a new release?

**Comment by cdiacon** [comment]
@steverobbins yes, should be about by the end of next week.
