### ISSUE TITLE
Error throws sometime

### ISSUE THREAD

**Issue by alphatests** [dotmailer/dotmailer-magento-extension#285]
Magento version 1.9.2.4 
Sometime mail is not received and in exception log this error shows

```
exception 'Zend_Mail_Protocol_Exception' with message 'Connection timed out' in /var/www/juliab2/lib/Zend/Mail/Protocol/Abstract.php:277
Stack trace:
#0 /var/www/juliab2/lib/Zend/Mail/Protocol/Smtp.php(167): Zend_Mail_Protocol_Abstract->_connect('tcp://r2-smtp.d...')
#1 /var/www/juliab2/lib/Zend/Mail/Transport/Smtp.php(199): Zend_Mail_Protocol_Smtp->connect()
#2 /var/www/juliab2/lib/Zend/Mail/Transport/Abstract.php(348): Zend_Mail_Transport_Smtp->_sendMail()
#3 /var/www/juliab2/lib/Zend/Mail.php(1194): Zend_Mail_Transport_Abstract->send(Object(Zend_Mail))
#4 /var/www/juliab2/app/code/community/Dotdigitalgroup/Email/Model/Email/Template.php(95): Zend_Mail->send(Object(Zend_Mail_Transport_Smtp))
#5 /var/www/juliab2/app/code/core/Mage/Core/Model/Email/Template.php(508): Dotdigitalgroup_Email_Model_Email_Template->send('test1@gmail.c...', 'Signature Stitc...', Array)
#6 /var/www/juliab2/app/code/local/Shero/Po/Helper/Email.php(219): Mage_Core_Model_Email_Template->sendTransactional('8', Array, 'test1@gmail.c...', 'Signature Stitc...', Array, '0')
#7 /var/www/juliab2/app/code/local/Shero/Po/Helper/Email.php(62): Shero_Po_Helper_Email->send_email('8', Array, Array)
#8 /var/www/juliab2/app/code/local/Shero/Po/Model/Observer.php(257): Shero_Po_Helper_Email->sendOrderEmailToVendor('154', Object(Amasty_Orderattr_Model_Sales_Order))
#9 /var/www/juliab2/app/code/community/Mage/Core/Model/App.php(1290): Shero_Po_Model_Observer->salesOrderSaveAfterAdmin(Object(Varien_Event_Observer))
#10 /var/www/juliab2/app/code/community/Mage/Core/Model/App.php(1260): Mage_Core_Model_App->_callObserverMethod(Object(Shero_Po_Model_Observer), 'salesOrderSaveA...', Object(Varien_Event_Observer))
#11 /var/www/juliab2/app/Mage.php(449): Mage_Core_Model_App->dispatchEvent('sales_order_sav...', Array)
#12 /var/www/juliab2/app/code/core/Mage/Core/Model/Abstract.php(466): Mage::dispatchEvent('sales_order_sav...', Array)
#13 /var/www/juliab2/app/code/core/Mage/Sales/Model/Order.php(2228): Mage_Core_Model_Abstract->_afterSave()
#14 /var/www/juliab2/app/code/core/Mage/Core/Model/Abstract.php(319): Mage_Sales_Model_Order->_afterSave()
#15 /var/www/juliab2/app/code/core/Mage/Adminhtml/controllers/Sales/OrderController.php(284): Mage_Core_Model_Abstract->save()
#16 /var/www/juliab2/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Sales_OrderController->addCommentAction()
#17 /var/www/juliab2/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('addComment')
#18 /var/www/juliab2/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#19 /var/www/juliab2/app/code/community/Mage/Core/Model/App.php(346): Mage_Core_Controller_Varien_Front->dispatch()
#20 /var/www/juliab2/app/Mage.php(685): Mage_Core_Model_App->run(Array)
#21 /var/www/juliab2/index.php(69): Mage::run('', 'store')
#22 {main}
```

**Comment by adeelq** [comment]
@alphatests How often have you experienced this? Which port you are using?

**Comment by adeelq** [comment]
Already fixed or unable to replicate
