### ISSUE TITLE
Unrecognized method 'getFirstItem()' when saving product review

### ISSUE THREAD

**Issue by erikhansen** [dotmailer/dotmailer-magento-extension#37]
# Steps to reproduce

* Login as customer on frontend and leave review on a product
* Login to admin, find review, change to "Approved" and save review: 
![edit_review___customer_reviews___reviews_and_ratings___catalog](https://cloud.githubusercontent.com/assets/129031/14504841/16ee0af4-017c-11e6-8e9a-22ffaac5bfee.png)
* You will see the following error in the error log: 
```
2016-04-13T18:29:21+00:00 DEBUG (7): Exception message: Unrecognized method 'getFirstItem()'
Trace: #0 /var/www/html/.modman/dotmailer-magento-extension/code/Dotdigitalgroup/Email/Model/Customer/Observer.php(204): Zend_Db_Select->__call('getFirstItem', Array)
#1 /var/www/html/.modman/dotmailer-magento-extension/code/Dotdigitalgroup/Email/Model/Customer/Observer.php(204): Varien_Db_Select->getFirstItem()
#2 /var/www/html/app/code/core/Mage/Core/Model/App.php(1343): Dotdigitalgroup_Email_Model_Customer_Observer->reviewSaveAfter(Object(Varien_Event_Observer))
#3 /var/www/html/app/code/core/Mage/Core/Model/App.php(1322): Mage_Core_Model_App->_callObserverMethod(Object(Dotdigitalgroup_Email_Model_Customer_Observer), 'reviewSaveAfter', Object(Varien_Event_Observer))
#4 /var/www/html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('review_save_aft...', Array)
#5 /var/www/html/app/code/core/Mage/Core/Model/Abstract.php(466): Mage::dispatchEvent('review_save_aft...', Array)
#6 /var/www/html/app/code/core/Mage/Core/Model/Abstract.php(319): Mage_Core_Model_Abstract->_afterSave()
#7 /var/www/html/app/code/core/Mage/Adminhtml/controllers/Catalog/Product/ReviewController.php(130): Mage_Core_Model_Abstract->save()
#8 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Catalog_Product_ReviewController->saveAction()
#9 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('save')
#10 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/html/app/Mage.php(685): Mage_Core_Model_App->run(Array)
#13 /var/www/html/index.php(132): Mage::run('', 'store')
#14 {main}
```

**Comment by cdiacon** [comment]
HI @erikhansen indeed this was fixed now in the commit above.

**Comment by erikhansen** [comment]
Thanks for the fast turnaround! I applied this fix and confirmed that this fixed my issue.
